routes/manajemen.py
from flask import Blueprint, render_template, session, redirect, url_for, flash
from db import get_db_connection

from .decorators import role_required

manajemen = Blueprint("manajemen", __name__)

@manajemen.route("/super/manajemenpengguna")
@role_required('super')
def manajemenSuper():
    if 'email' not in session:
        return redirect(url_for('auth.login'))
    
    connection = get_db_connection()
    with connection.cursor() as cursor:
        cursor.execute("SELECT firstname, lastname, role, email FROM users WHERE role = 'user'")
        data = cursor.fetchall()
    connection.close()
    
    return render_template("super/manajemen-pengguna-super.html", data=data)

@manajemen.route("/delete_user/<string:email>", methods=['POST'])
def delete_user(email):
    connection = get_db_connection()
    with connection.cursor() as cursor:
        cursor.execute("DELETE FROM users WHERE email = %s", (email,))
        connection.commit()
    connection.close()
    flash("User deleted successfully!", "success")
    return redirect(url_for('manajemen.manajemenSuper'))

templates/super/data-sentimen-super.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="favicon.ico">
    <title>Aplikasi Analisis Sentimen - Data Sentimen</title>
    <!-- Simple bar CSS -->
    <link rel="stylesheet" href="../../static/css/simplebar.css">
    <!-- Fonts CSS -->
    <link
        href="https://fonts.googleapis.com/css2?family=Overpass:ital,wght@0,100;0,200;0,300;0,400;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,600;1,700;1,800;1,900&display=swap"
        rel="stylesheet">
    <!-- Icons CSS -->
    <link rel="stylesheet" href="../../static/css/feather.css">
    <link rel="stylesheet" href="../../static/css/dataTables.bootstrap4.css">
    <!-- Date Range Picker CSS -->
    <link rel="stylesheet" href="../../static/css/daterangepicker.css">
    <!-- App CSS -->
    <link rel="stylesheet" href="../../static/css/app-light.css" id="lightTheme">
    <!-- Sweet Alert -->
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
</head>

<body class="vertical  light  ">
    <div class="wrapper">
        
        <!-- Navbar --> {% include 'super/layouts/_navbar_super.html' %}
        <!-- Sidebar --> {% include 'super/layouts/_sidebar_super.html' %}

        <main role="main" class="main-content">
            <div class="container-fluid">
                <div class="row justify-content-center">
                    <div class="col-12">
                        <div class="row">
                            <div class="col-6 d-flex">
                                <h2 class="mb-2 page-title">Data Sentimen</h2>
                            </div>
                            <div class="col-6 d-flex justify-content-end">
                                <form action="/super/datasentimen?status=import_success" method="post"
                                    enctype="multipart/form-data" id="uploadForm">
                                    <input type="file" name="file" class="file-upload-default" style="display: none;"
                                        accept=".csv" required
                                        onchange="document.getElementById('uploadForm').submit();" />
                                    <button type="button" class="file-upload-browse btn mb-2 mr-2 btn-outline-primary"
                                        onclick="document.querySelector('input[type=file]').click();">
                                        <span class="fe fe-file-plus fe-16 mr-2"></span>Import Data CSV File
                                    </button>
                                </form>
                                <form action="/super/hapusdata?status=delete_success" method="post" id="deleteForm">
                                    <button type="submit" class="file-upload-browse btn mb-2 btn-outline-danger"
                                        id="deleteButton">
                                        <span class="fe fe-trash-2 fe-16 mr-2"></span>Hapus Dataset
                                    </button>
                                </form>
                            </div>
                        </div>

                        <!-- Overlay atau animasi loading -->
                        <div id="loadingOverlay"
                            style="display: none; position: fixed; top: 0; left: 0; width: 100%; height: 100%; background: rgba(0, 0, 0, 0.5); z-index: 9999; text-align: center; color: white;">
                            <div
                                style="position: absolute; top: 50%; left: 50%; transform: translate(-50%, -50%); font-size: 1.5em;">
                                Memproses data...
                            </div>
                        </div>

                        <div class="row my-4">
                            <!-- Small table -->
                            <div class="col-md-12">
                                <div class="card shadow">
                                    <div class="card-body">

                                        <!-- table -->
                                        <table class="table datatables" id="dataTable-1">
                                            <thead>
                                                <tr>
                                                    <th>#</th>
                                                    <th>Username</th>
                                                    <th>Text</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                {% if data %}
                                                {% for row in data %}
                                                <tr>
                                                    <td>{{ loop.index }}</td>
                                                    <td>{{ row['username'] }}</td>
                                                    <td>{{ row['full_text'] }}</td>
                                                </tr>
                                                {% endfor %}
                                                {% else %}
                                                <tr>
                                                    <td colspan="6" class="text-center">No data available</td>
                                                </tr>
                                                {% endif %}
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div> <!-- simple table -->

                        </div> <!-- end section -->
                    </div> <!-- .col-12 -->
                </div> <!-- .row -->
            </div> <!-- .container-fluid -->

        </main> <!-- main -->
    </div> <!-- .wrapper -->
    <script src="../../static/js/jquery.min.js"></script>
    <script src="../../static/js/popper.min.js"></script>
    <script src="../../static/js/moment.min.js"></script>
    <script src="../../static/js/bootstrap.min.js"></script>
    <script src="../../static/js/simplebar.min.js"></script>
    <script src='../../static/js/daterangepicker.js'></script>
    <script src='../../static/js/jquery.stickOnScroll.js'></script>
    <script src="../../static/js/tinycolor-min.js"></script>
    <script src="../../static/js/config.js"></script>
    <script src='../../static/js/jquery.dataTables.min.js'></script>
    <script src='../../static/js/dataTables.bootstrap4.min.js'></script>
    <script src='../../static/js/file-upload.js'></script>
    <script>
        $('#dataTable-1').DataTable({
            autoWidth: true,
            "lengthMenu": [
                [16, 32, 64, -1],
                [16, 32, 64, "All"]
            ]
        });
    </script>
    <script src="../../static/js/apps.js"></script>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-56159088-1"></script>
    <script>
        window.dataLayer = window.dataLayer || [];

        function gtag() {
            dataLayer.push(arguments);
        }
        gtag('js', new Date());
        gtag('config', 'UA-56159088-1');
    </script>

    <!-- Sweet Alert -->
    <script>
        // Cek apakah ada parameter `status` di URL
        const urlParams = new URLSearchParams(window.location.search);
        const status = urlParams.get('status');

        // Tampilkan Sweet Alert berdasarkan status
        if (status === 'import_success') {
            Swal.fire({
                icon: 'success',
                title: 'Dataset berhasil diimport!',
                showConfirmButton: false,
                timer: 2000
            });
        } else if (status === 'delete_success') {
            Swal.fire({
                icon: 'success',
                title: 'Dataset berhasil dihapus!',
                showConfirmButton: false,
                timer: 2000
            });
        } else if (status === 'preprocess_success') {
            Swal.fire({
                icon: 'success',
                title: 'Pre-processing berhasil dilakukan!',
                showConfirmButton: false,
                timer: 2000
            });
        }
    </script>

    <script>
        // Tambahkan event listener untuk menampilkan loading
        document.getElementById("preprocessingForm").onsubmit = function () {
            // Mengubah teks tombol
            const button = document.getElementById("preprocessingButton");
            button.disabled = true;
            button.innerHTML = "Sedang Memproses...";

            // Menampilkan overlay loading
            document.getElementById("loadingOverlay").style.display = "block";
        };
    </script>
</body>

</html>

templates/super/hasil-analisis-super.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="favicon.ico">
    <title>Aplikasi Analisis Sentimen - Hasil Analisis</title>
    <!-- Simple bar CSS -->
    <link rel="stylesheet" href="/static/css/simplebar.css">
    <!-- Fonts CSS -->
    <link
        href="https://fonts.googleapis.com/css2?family=Overpass:ital,wght@0,100;0,200;0,300;0,400;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,600;1,700;1,800;1,900&display=swap"
        rel="stylesheet">
    <!-- Icons CSS -->
    <link rel="stylesheet" href="/static/css/feather.css">
    <link rel="stylesheet" href="/static/css/dataTables.bootstrap4.css">
    <!-- Date Range Picker CSS -->
    <link rel="stylesheet" href="/static/css/daterangepicker.css">
    <!-- App CSS -->
    <link rel="stylesheet" href="/static/css/app-light.css" id="lightTheme">
</head>

<body class="vertical  light  ">
    <div class="wrapper">

        <!-- Navbar --> {% include 'super/layouts/_navbar_super.html' %}
        <!-- Sidebar --> {% include 'super/layouts/_sidebar_super.html' %}

        <main role="main" class="main-content">
            <div class="container-fluid">
                <div class="row justify-content-center">
                    <div class="col-12">
                        <div class="row">
                            <div class="col-6 d-flex">
                                <h2 class="mb-2 page-title">Hasil Analisis</h2>
                            </div>
                        </div>

                        <div class="row my-4">
                            <div class="col-md-12">
                                <div class="card shadow">
                                    <div class="card-body">
                                        <h2 class="h4 text-muted mb-4">Model Random Forest</h2>
                                        <p class="mb-1"><strong>Akurasi</strong></p>
                                        <div class="progress mb-3">
                                            <div class="progress-bar" role="progressbar" style="width: {{ accuracy }}%;"
                                                aria-valuenow="{{ accuracy }}" aria-valuemin="0" aria-valuemax="100">
                                                {{ accuracy }}%
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="row my-4">
                            <div class="col-md-6 d-flex align-items-stretch">
                                <div class="card shadow w-100">
                                    <div class="card-body">
                                        <h2 class="h4 text-muted mb-4">Classification Report</h2>
                                        {% for label, metrics in report.items() if label != 'accuracy' %}
                                            <p>
                                                <strong>{{ label.capitalize() }}</strong>:<br>
                                                - Precision: {{ metrics['precision'] }}%<br>
                                                - Recall: {{ metrics['recall'] }}%<br>
                                            </p>
                                        {% endfor %}
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6 d-flex align-items-stretch">
                                <div class="card shadow w-100">
                                    <div class="card-body">
                                        <h2 class="h4 text-muted mb-4">Confusion Matrix</h2>
                                        <div class="text-center">
                                            <img src="{{ url_for('static', filename='images/confusion_matrix.png') }}"
                                                alt="Confusion Matrix" class="img-fluid" style="max-width: 90%;">
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="row mt-2 mb-4">
                            <div class="col-md-12">
                                <div class="card shadow">
                                    <div class="card-body">
                                        <h2 class="h4 text-muted mb-4 text-left">WordCloud Sentimen Positif</h2>
                                        <div class="text-center">
                                            <figure class="figure">
                                                <img src="{{ url_for('static', filename=wordcloud_images['positive']) }}"
                                                    alt="WordCloud Positif" class="img-fluid" style="max-width: 100%;">
                                            </figure>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="row my-4">
                            <div class="col-md-12">
                                <div class="card shadow">
                                    <div class="card-body">
                                        <h2 class="h4 text-muted mb-4 text-left">WordCloud Sentimen Negatif</h2>
                                        <div class="text-center">
                                            <figure class="figure">
                                                <img src="{{ url_for('static', filename=wordcloud_images['negative']) }}"
                                                    alt="WordCloud Negatif" class="img-fluid" style="max-width: 100%;">
                                            </figure>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="row my-4">
                            <div class="col-md-12">
                                <div class="card shadow">
                                    <div class="card-body">
                                        <h2 class="h4 text-muted mb-4 text-left">WordCloud Sentimen Netral</h2>
                                        <div class="text-center">
                                            <figure class="figure">
                                                <img src="{{ url_for('static', filename=wordcloud_images['neutral']) }}"
                                                    alt="WordCloud Netral" class="img-fluid" style="max-width: 100%;">
                                            </figure>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>


                    </div> <!-- .col-12 -->
                </div> <!-- .row -->
            </div> <!-- .container-fluid -->
        </main> <!-- main -->
    </div> <!-- .wrapper -->
    <script src="/static/js/jquery.min.js"></script>
    <script src="/static/js/popper.min.js"></script>
    <script src="/static/js/moment.min.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
    <script src="/static/js/simplebar.min.js"></script>
    <script src='/static/js/daterangepicker.js'></script>
    <script src='/static/js/jquery.stickOnScroll.js'></script>
    <script src="/static/js/tinycolor-min.js"></script>
    <script src="/static/js/config.js"></script>
    <script src='/static/js/jquery.dataTables.min.js'></script>
    <script src='/static/js/dataTables.bootstrap4.min.js'></script>
    <script src='/static/js/file-upload.js'></script>
    <script>
        $('#dataTable-1').DataTable({
            autoWidth: true,
            "lengthMenu": [
                [16, 32, 64, -1],
                [16, 32, 64, "All"]
            ]
        });
    </script>
    <script src="/static/js/apps.js"></script>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-56159088-1"></script>
    <script>
        window.dataLayer = window.dataLayer || [];

        function gtag() {
            dataLayer.push(arguments);
        }
        gtag('js', new Date());
        gtag('config', 'UA-56159088-1');
    </script>


</body>

</html>

templates/super/manajemen-pengguna-super.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="favicon.ico">
    <title>Aplikasi Analisis Sentimen - Manajemen Pengguna</title>
    <!-- Simple bar CSS -->
    <link rel="stylesheet" href="/static/css/simplebar.css">
    <!-- Fonts CSS -->
    <link
        href="https://fonts.googleapis.com/css2?family=Overpass:ital,wght@0,100;0,200;0,300;0,400;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,600;1,700;1,800;1,900&display=swap"
        rel="stylesheet">
    <!-- Icons CSS -->
    <link rel="stylesheet" href="/static/css/feather.css">
    <link rel="stylesheet" href="/static/css/dataTables.bootstrap4.css">
    <!-- Date Range Picker CSS -->
    <link rel="stylesheet" href="/static/css/daterangepicker.css">
    <!-- App CSS -->
    <link rel="stylesheet" href="/static/css/app-light.css" id="lightTheme">
    <!-- Sweet Alert -->
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <!-- Option 1: Include in HTML -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
</head>

<body class="vertical  light  ">
    <div class="wrapper">

        <!-- Navbar --> {% include 'super/layouts/_navbar_super.html' %}
        <!-- Sidebar --> {% include 'super/layouts/_sidebar_super.html' %}

        <main role="main" class="main-content">
            <div class="container-fluid">
                <div class="row justify-content-center">
                    <div class="col-12">
                        <div class="row">
                            <div class="col-6 d-flex">
                                <h2 class="mb-2 page-title">Manajemen User</h2>
                            </div>
                        </div>
                        <div class="row my-4">
                            <!-- Small table -->
                            <div class="col-md-12">
                                <div class="card shadow">
                                    <div class="card-body">
                                        <!-- table -->
                                        <table class="table datatables" id="dataTable-1">
                                            <thead>
                                                <tr>
                                                    <th>#</th>
                                                    <th>Nama Depan</th>
                                                    <th>Nama Belakang</th>
                                                    <th>Email</th>
                                                    <th>Action</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                {% if data %}
                                                {% for row in data %}
                                                <tr>
                                                    <td>{{ loop.index }}</td>
                                                    <td>{{ row['firstname'] }}</td>
                                                    <td>{{ row['lastname'] }}</td>
                                                    <td>{{ row['email'] }}</td>
                                                    <td>
                                                        <form action="{{ url_for('manajemen.delete_user', email=row['email']) }}" method="post" onsubmit="return confirm('Are you sure you want to delete this user?');">
                                                            <button type="submit" class="btn btn-outline-danger btn-sm">
                                                                <i class="bi bi-trash-fill bi-middle"></i>
                                                            </button>
                                                        </form>
                                                    </td>
                                                    {% endfor %}
                                                    {% else %}
                                                </tr>
                                                <tr>
                                                    <td colspan="6" class="text-center">No data available</td>
                                                </tr>
                                                {% endif %}
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div> <!-- simple table -->
                        </div> <!-- end section -->
                    </div> <!-- .col-12 -->
                </div> <!-- .row -->
            </div> <!-- .container-fluid -->

        </main> <!-- main -->
    </div> <!-- .wrapper -->
    <script src="/static/js/jquery.min.js"></script>
    <script src="/static/js/popper.min.js"></script>
    <script src="/static/js/moment.min.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
    <script src="/static/js/simplebar.min.js"></script>
    <script src='/static/js/daterangepicker.js'></script>
    <script src='/static/js/jquery.stickOnScroll.js'></script>
    <script src="/static/js/tinycolor-min.js"></script>
    <script src="/static/js/config.js"></script>
    <script src='/static/js/jquery.dataTables.min.js'></script>
    <script src='/static/js/dataTables.bootstrap4.min.js'></script>
    <script src='/static/js/file-upload.js'></script>
    <script>
        $('#dataTable-1').DataTable({
            autoWidth: true,
            "lengthMenu": [
                [16, 32, 64, -1],
                [16, 32, 64, "All"]
            ]
        });
    </script>
    <script src="/static/js/apps.js"></script>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-56159088-1"></script>
    <script>
        window.dataLayer = window.dataLayer || [];

        function gtag() {
            dataLayer.push(arguments);
        }
        gtag('js', new Date());
        gtag('config', 'UA-56159088-1');
    </script>

</body>

</html>